#!/bin/bash

#Information Gathering
whois
nslookup
dig
host
sublist3r
amass
asstefinder
findomain
massdns
httprobe
nmap
aquatone
aqutone-discover
gau
hakrawler
github-search
gitrob
fierce
dirsearch
ffuf
gowitness
nuclei
metagoofil
theHarvester
recon-ng
dnsenum
dnsrecon
shodan
censys
spiderfoot

#Subdomain Enumeration
subfinder
waymore
subjack

#Vulnerability Scanning
xsstrike
gf
git-secrets
ffuf

#Miscellaneous Tools
arjun
unfurl
dalfox
gospider
meg
wfuzz
wafw00f
wpscanner
cloud_enum
gobuster
masscan
paramspider

#Network and DNS Tools
dnswalk
dnsx
dnsgen
dnswalidator
httx


Subdomainer
chaos
asstefinder
frogy